"""add call_logs sent_replies email_draft_states outbound_messages tables

Revision ID: 0719eaccbdef
Revises: 78c5397c94ee
Create Date: 2026-04-06 06:33:23.087683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0719eaccbdef'
down_revision: Union[str, Sequence[str], None] = '78c5397c94ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_draft_states',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_email_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('draft_review_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending_review', 'revision_requested', 'approved', 'sent', 'abandoned')", name='ck_email_draft_state_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_draft_active_unique', 'email_draft_states', ['user_id', 'thread_id'], unique=True, postgresql_where=sa.text("status IN ('pending_review', 'revision_requested', 'approved')"))
    op.create_index(op.f('ix_email_draft_states_user_id'), 'email_draft_states', ['user_id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('twilio_message_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name='ck_outbound_message_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_outbound_message_dedup')
    )
    op.create_index(op.f('ix_outbound_messages_dedup_key'), 'outbound_messages', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_outbound_messages_user_id'), 'outbound_messages', ['user_id'], unique=False)
    op.create_table('sent_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gmail_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'thread_id', name='uq_sent_reply_user_thread')
    )
    op.create_index(op.f('ix_sent_replies_thread_id'), 'sent_replies', ['thread_id'], unique=False)
    op.create_index(op.f('ix_sent_replies_user_id'), 'sent_replies', ['user_id'], unique=False)
    op.create_table('call_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('call_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurrence_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('root_call_log_id', sa.Integer(), nullable=True),
    sa.Column('replaced_call_log_id', sa.Integer(), nullable=True),
    sa.Column('origin_window_id', sa.Integer(), nullable=True),
    sa.Column('twilio_call_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('last_twilio_sequence_number', sa.Integer(), nullable=True),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('commitments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('call_outcome_confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accomplishments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tomorrow_intention', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reflection_confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recap_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkin_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("call_outcome_confidence IN ('clear', 'partial', 'none') OR call_outcome_confidence IS NULL", name='ck_call_log_call_outcome_confidence'),
    sa.CheckConstraint("call_type IN ('morning', 'afternoon', 'evening', 'on_demand')", name='ck_call_log_call_type'),
    sa.CheckConstraint("occurrence_kind IN ('planned', 'on_demand', 'retry', 'rescheduled')", name='ck_call_log_occurrence_kind'),
    sa.CheckConstraint("reflection_confidence IN ('clear', 'partial', 'none') OR reflection_confidence IS NULL", name='ck_call_log_reflection_confidence'),
    sa.CheckConstraint("status IN ('scheduled', 'dispatching', 'ringing', 'in_progress', 'completed', 'missed', 'deferred', 'cancelled', 'skipped')", name='ck_call_log_status'),
    sa.ForeignKeyConstraint(['origin_window_id'], ['call_windows.id'], ),
    sa.ForeignKeyConstraint(['replaced_call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['root_call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_log_ondemand_unique', 'call_logs', ['user_id'], unique=True, postgresql_where=sa.text("call_type = 'on_demand' AND status = 'scheduled'"))
    op.create_index('ix_call_log_planned_unique', 'call_logs', ['user_id', 'call_type', 'call_date'], unique=True, postgresql_where=sa.text("occurrence_kind = 'planned'"))
    op.create_index(op.f('ix_call_logs_call_date'), 'call_logs', ['call_date'], unique=False)
    op.create_index(op.f('ix_call_logs_twilio_call_sid'), 'call_logs', ['twilio_call_sid'], unique=False)
    op.create_index(op.f('ix_call_logs_user_id'), 'call_logs', ['user_id'], unique=False)
    # NOTE: idx_tasks_title_trgm GIN index is managed via raw SQL in the tasks migration.
    # Alembic autogenerate incorrectly detects it as removed — do NOT drop it here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_user_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_twilio_call_sid'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_call_date'), table_name='call_logs')
    op.drop_index('ix_call_log_planned_unique', table_name='call_logs', postgresql_where=sa.text("occurrence_kind = 'planned'"))
    op.drop_index('ix_call_log_ondemand_unique', table_name='call_logs', postgresql_where=sa.text("call_type = 'on_demand' AND status = 'scheduled'"))
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_sent_replies_user_id'), table_name='sent_replies')
    op.drop_index(op.f('ix_sent_replies_thread_id'), table_name='sent_replies')
    op.drop_table('sent_replies')
    op.drop_index(op.f('ix_outbound_messages_user_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_dedup_key'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_email_draft_states_user_id'), table_name='email_draft_states')
    op.drop_index('ix_email_draft_active_unique', table_name='email_draft_states', postgresql_where=sa.text("status IN ('pending_review', 'revision_requested', 'approved')"))
    op.drop_table('email_draft_states')
    # ### end Alembic commands ###
