"""create_call_windows_table

Revision ID: 8a2e0b6728c1
Revises: edd68c66c582
Create Date: 2026-04-06 06:11:17.924248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '8a2e0b6728c1'
down_revision: Union[str, Sequence[str], None] = 'edd68c66c582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_windows',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('window_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("window_type IN ('morning', 'afternoon', 'evening')", name='ck_call_window_window_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'window_type', name='uq_user_window_type')
    )
    op.create_index(op.f('ix_call_windows_user_id'), 'call_windows', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Attach the reusable set_updated_at trigger to the new table.
    op.execute(
        sa.text("""
        CREATE TRIGGER trg_call_windows_set_updated_at
        BEFORE UPDATE ON call_windows
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the trigger before dropping the table.
    op.execute(
        sa.text("DROP TRIGGER IF EXISTS trg_call_windows_set_updated_at ON call_windows;")
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_windows_user_id'), table_name='call_windows')
    op.drop_table('call_windows')
    # ### end Alembic commands ###
