"""extend_user_model_onboarding_fields

Revision ID: edd68c66c582
Revises: ad88e9037eb6
Create Date: 2026-04-06 06:02:56.263925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'edd68c66c582'
down_revision: Union[str, Sequence[str], None] = 'ad88e9037eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('onboarding_complete', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('google_access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('google_token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('google_granted_scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_opener_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_approach', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('consecutive_active_days', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('last_active_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('last_checkin_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_weekly_summary_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_user_whatsapp_message_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_user_whatsapp_message_at')
    op.drop_column('users', 'last_weekly_summary_sent_at')
    op.drop_column('users', 'last_checkin_template')
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'consecutive_active_days')
    op.drop_column('users', 'last_approach')
    op.drop_column('users', 'last_opener_id')
    op.drop_column('users', 'google_granted_scopes')
    op.drop_column('users', 'google_token_expiry')
    op.drop_column('users', 'google_refresh_token_encrypted')
    op.drop_column('users', 'google_access_token_encrypted')
    op.drop_column('users', 'onboarding_complete')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
